config/routes.rb
Rails.application.routes.draw do
  root to: 'blog/articles#index'
  devise_for :users
  resources :users

  # This gives you:
  # /blog
  # /blog/:name-of-the-article
  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end


end

app/models/blog/article.rb
class Blog::Article
  include ActiveModel::Model
  attr_accessor :title, :content, :created_at, :permalink, :author, :tags, :description

  # Used for ATOM-feed id
  def id
    @permalink.to_i
  end

  def content
    remove_yaml_frontmatter_from @content
  end

  def excerpt
    content.split('<!--more-->').first
  end

  def body
    content.split('<!--more-->').last
  end

  def has_more_text?
    content != excerpt
  end

  def created_at
    @created_at.to_date
  end

  def to_param
    @permalink.parameterize
  end

  # Query methods
  def self.all
    article_files.reverse.map do |file|
      self.new extract_data_from(file)
    end
  end

  def self.find_by_name(name)
    file = find_file_by(name)
    self.new extract_data_from(file)
  end

  private
  def self.article_files
    sort_by_id Dir.glob(articles_path + '/' + '*.md')
  end

  def self.sort_by_id(files)
    files.sort_by { |x| File.basename(x, '.*').to_i }
  end

  def self.find_file_by(name)
    id = article_files.index { |x| x =~ /#{name}.md/ }
    article_files[id]
  end

  def self.articles_path
    Rails.root.join('app', 'views', 'blog', 'published').to_s
  end

  # Content retrieval
  def self.extract_data_from(file)
    {
      content: File.read(file),
      permalink: File.basename(file, '.*')
    }.merge(yaml_frontmatter_metadata_from(file))
  end

  def self.yaml_frontmatter_metadata_from(file)
    YAML.load_file(file)
  end

  def remove_yaml_frontmatter_from(text)
    text.sub(/^\s*---(.*?)---\s/m, "")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog/articles_controller.rb
class Blog::ArticlesController < ApplicationController
  def index
    @articles = Blog::Article.all
  end

  def show
    @article = Blog::Article.find_by_name(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(title = nil)
    if title.present?
      content_for :title, title
    else
      content_for?(:title) ? APP_CONFIG['default_title'] + ' | ' + content_for(:title) : APP_CONFIG['default_title']
    end
  end

  def meta_keywords(tags = nil)
    if tags.present?
      content_for :meta_keywords, tags
    else
      content_for?(:meta_keywords) ? content_for(:meta_keywords) : APP_CONFIG['meta_keywords']
    end
  end

  def meta_description(desc = nil)
    if desc.present?
      content_for :meta_description, desc
    else
      content_for?(:meta_description) ? content_for(:meta_description) : APP_CONFIG['meta_description']
    end
  end

end

app/helpers/blog_helper.rb
module BlogHelper

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true,
                                  :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :lax_html_blocks => true,
    }
    Redcarpet::Markdown.new(coderayified, options).render(text).html_safe
  end

  def preserve_markdown(text) # Used to get the indentation right in the <pre> code blocks with Haml
    preserve markdown(text)
  end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blog/articles/_meta.html.haml
.meta
  %time{ pubdate: "", datetime: article.created_at }
    = l article.created_at, format: :long
  by
  = article.author

app/views/blog/articles/index.html.haml
- title "Modern Marketer"
%header.intro-header
  .container
    .row
      %div{class: 'col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1'}
        .site-heading
          .row
            %div{class: 'col-md-7 col-md-offset-1'}
              %h1.text-left Modern Marketing
              %span{class: 'subheading text-left'} A how-to blog for the modern marketer.
            %div{class: 'col-md-3 topspace20'}
              = link_to image_tag("/assets/shift.png" ,:width => 160, :alt => "Promo Image", :class => "img-responsive center-block center-vert topspace20"), root_path

- @articles.each do |article|
  %article
    .container
      .row
        %div{class: 'col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1'}
          %h1= link_to article.title, blog_article_path(article)
          = render partial: "meta", locals: { article: article }
          = preserve_markdown article.excerpt
          - if article.has_more_text?
            %p= link_to "Continue reading →", blog_article_path(article)

app/views/blog/articles/show.html.haml
- title @article.title
- meta_description @article.description
- meta_keywords @article.tags

%header.intro-header
  .container
    .row
      %div{class: 'col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1'}
        .page-heading
          .row
            %div{class: 'col-md-12'}
              .post-header
                %h1.text-left= @article.title
                %span{class: 'subheading text-left'}
                  = render partial: "meta", locals: { article: @article }
                  = preserve_markdown @article.excerpt


%article
  .container
    .row
      %div{class: 'col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1'}
        = preserve_markdown @article.body
        %hr
        %p.action= link_to "← Back to Overview", blog_articles_path

app/views/layouts/_footer.html.erb
<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="https://linkedin.com/in/austinbagley">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="https://instagram.com/austinbagley">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/austinbagley">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Austin Bagley 2016</p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->

            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                  <%= link_to image_tag("/assets/ablogowhite2.svg" , :alt => "Promo Image", :class => "img-responsive"), root_path, class: 'navbar-brand' %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <%= render 'layouts/navigation_links' %>

                </ul>
            </div>

        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
    <%= link_to 'Blog', root_path %>
</li>
<li>
    <%= link_to 'About', page_path('about') %>
</li>
<li>
    <%= link_to 'Contact', page_path('contact') %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= title %></title>
    <meta name="keywords" content="<%= meta_keywords %>" />
    <meta name="description" content="<%= meta_description %>" />
    <link rel="canonical" href="<%= "#{APP_CONFIG["default_url"] + url_for(:page => params[:page]) }" %>" />
    <noscript>
      <meta http-equiv="refresh" content="2;url=https://austinbagley.com/nojs.html">
    </noscript>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, :defer => "true"  %>
    <%= csrf_meta_tags %>

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<% title "BYU MBA" %>
<% meta_description "Austin Bagley is a BYU MBA of 2016, Startup Marketer at @LatitudeTours, Associate Brand Manager at @CampbellSoupCo, and father of two." %>
<% meta_keywords "Austin Bagley, BYU, MBA, Analytics, Marketing, Maverik, Campbell Soup, Latitude" %>
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header">
   <div class="container">
       <div class="row">
           <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
               <div class="site-heading">
                   <h1>About Me</h1>
                   <hr class="small">
                   <span class="subheading">This is what I do.</span>
               </div>
           </div>
       </div>
   </div>
</header>


<!-- Main Content -->
<div class="container">
   <div class="row">
       <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
       </div>
   </div>
</div>

<!-- Projects Row -->
<div class="container">
  <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <h1>Work</h1>
        <span class="subheading">This is what I've done.</span>
      </div>
    </div>
  <div class="row topspace20">
      <div class="col-md-4 col-md-offset-2 portfolio-item">

          <a href="#">
              <img class="img-responsive" src="/assets/latitude.jpg" alt="">
          </a>
          <h3>
              <a href="#">Latitude</a>
          </h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
      </div>
      <div class="col-md-4 portfolio-item">
          <a href="#">
              <img class="img-responsive" src="/assets/teamchallenge.jpg" alt="">
          </a>
          <h3>
              <a href="#">Team Challenge</a>
          </h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-2 portfolio-item">
          <a href="#">
              <img class="img-responsive" src="/assets/cougarcapital.jpg" alt="">
          </a>
          <h3>
              <a href="#">Cougar Capital</a>
          </h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
      </div>
      <div class="col-md-4 portfolio-item">
          <a href="#">
              <img class="img-responsive" src="/assets/campbell.jpg" alt="">
          </a>
          <h3>
              <a href="#">Campbell Soup</a>
          </h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
      </div>
    </div>
    <div class="row">

      <div class="col-md-4 col-md-offset-2 portfolio-item">
          <a href="#">
              <img class="img-responsive" src="/assets/mbama.jpg" alt="">
          </a>
          <h3>
              <a href="#">BYU MBA Marketing</a>
          </h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
      </div>
      <div class="col-md-4 portfolio-item">
          <a href="#">
              <img class="img-responsive" src="/assets/maverik.jpg" alt="">
          </a>
          <h3>
              <a href="#">Maverik</a>
          </h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
      </div>
  </div>
</div>

app/views/pages/contact.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('http://ironsummitmedia.github.io/startbootstrap-clean-blog/img/contact-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Contact Me</h1>
                    <hr class="small">
                    <span class="subheading">Have questions? I have answers (maybe).</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
            <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
            <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
            <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
            <form name="sentMessage" id="contactForm" novalidate>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Name</label>
                        <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Email Address</label>
                        <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Phone Number</label>
                        <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Message</label>
                        <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <br>
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="submit" class="btn btn-default">Send</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

app/views/pages/post.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-color: #E45043;">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1>Why modern marketers need to be full-stack integrators</h1>
                    <h2 class="subheading">We're marketing in a connected, digital world.</h2>
                    <span class="meta">Posted by <a href="#">Austin</a> on March 24, 2016</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

<blockquote>
<p>With the complexity of today&#8217;s marketing stack, modern marketers need to be full-stack integrators: combining deep-level brand management with the ability to deliver an integrated consumer acquisition &amp; retention process across a layer of technologies.</p>
</blockquote>
<p>A great <a href="http://techcrunch.com/2014/11/08/the-rise-and-fall-of-the-full-stack-developer/">article on TechCrunch</a> by <a href="https://twitter.com/peteryared">Peter Yared</a> a few years ago on the rise and fall of the full-stack developer mirrors the approach marketers should take: modern marketers should become a master integrators, not end-to-end experts. </p>

<h2 id="fullstackdevelopmentbecomesfullstackintegration">Full Stack Development becomes Full Stack Integration</h2>

<p>Once upon a time, websites were built end-to-end by a single programmer. As technology progressed and became difficult to manage, development was split across functional experts. Web technologies converged and became more manageable during Web 2.0 and single developers could employ an integrated stack to once again, create the entire application. Master LAMP, Rails, or MEAN and <a href="http://www.sitepoint.com/full-stack-developer/">you were golden</a>. </p>

<p>Not anymore. With machine learning, VR, native mobile platforms, advanced security, analytics, next-gen languages &amp; DevOps responsibilities at various levels of deployment, a &#8216;full-stack&#8217; developer can&#8217;t be expected to implement, let alone master the technology set available to modern applications. We need experts in these fields.</p>

<blockquote>
<p>The full-stack developer now needs to become the full-stack integrator.
In this brave new world, it is critical to have at least one person with at least a functional understanding of each of the composite parts who is also capable of connecting various tiers and working with each expert so that a feature can actually be delivered. In a way, these tier-connecting, bridge-building software architects — who are likely experts in only one or a couple of tiers — <strong>are less full stack developer and much more full stack integrator.</strong>
- Peter Yared [emphasis added]</p>
</blockquote>

<p>The same can be said of marketing. Master traditional/social/paid/content marketing and you&#8217;re a one-stop shop. Not anymore. We need to be customer-centric architects that can integrate technologies to create differentiating customer experiences. </p>

<h2 id="theneedformarketingstackintegrators">The Need for Marketing Stack Integrators</h2>

<p>Modern marketers need to keep a laser-focus on customers but add the ability to integrate a complex technology set to provide compelling experiences. </p>

<p>A recent example given at an Adobe Mobile presentation outlines the principle. A major hotel chain launched a large-scale marketing campaign aimed at their most loyal customers. The messaging was simple: check-in to the hotel with our app and be entered to win a million points. </p>

<p>The only problem? They hid the promotion behind a generic app experience. Follow the link from your <em>reservation email</em> and you&#8217;d be sent to the app front screen, which asked you to make, you guessed it, <em>another</em> room reservation. Only after persistent effort to navigate the app would you be able to locate the feature to check in. </p>

<p>Couldn&#8217;t there be a better way to integrate our mobile strategy with our marketing efforts to delight our most loyal customers? </p>

<p>In this example, the marketing strategy made sense: In order to retain our most valuable customers (those who book through our website) we will campaign to get our app on their device to encourage future bookings and we will encourage app engagement by providing added value (skip the line, check in from the phone). </p>

<p>Unfortunately, any time-saving customer delight moments were lost by missing the connection between a reservation-booked, on-premise customer and their mobile app.</p>

<h2 id="mastertheintegration">Master the Integration</h2>

<p>So who dropped the ball?
Marketing. </p>

<p>As the shepherds of the customer-experience, marketers need not only the ability to write a technology brief, but also the ability to talk shop with our development/vendor/partner team to make it come alive. Often, large companies will have individuals or teams dedicated to this, but if brand &amp; product marketers let outside team&#8217;s own the integration, the bridge between insight, strategy and execution will fall short. </p>

<p>I suggest that marketers do two things to increase their ability to integrate: learn the basics of software development and dive into the marketing landscape. </p>

<h3 id="learnthebasicsofsoftwaredevelopment">Learn the basics of software development</h3>

<p>At BYU where I completed my MBA recently, a number of entrepreneurial students spent their nights and weekends at a development bootcamp to improve their ability to work with their technical teams. I spent time time outside my marketing emphasis learning Apple&#8217;s Swift with a CS professor and learning Ruby on Rails and API creation as part of a <a href="https://latitudetours.com">tech startup team</a>. I&#8217;m no developer, but I can certainly speak the language now&#8211;and when our marketing site needs a feature, I don&#8217;t need to pull a developer off the product. There are a number of great resources for a quick-hitting education into nerd-land.</p>

<p>Check out a great post on Ray Wenderlich that will get you a sense of both iOS and Ruby on Rails web development all in one <a href="https://www.raywenderlich.com/85528/user-accounts-ios-ruby-rails-swift">tutorial</a>.</p>

<h3 id="diveintothemarketinglandscape">Dive Into the Marketing Landscape</h3>

<p>I&#8217;m always looking for more sources for marketing tech (please share), but here are a few go-to&#8217;s that are both on and off the beaten path:</p>

<h4 id="thestackieawards">The Stackie Awards</h4>

<p>I really like what <a href="http://martechconf.com/">MarTech</a> has done with the Stackie Awards, which consist of companies submitting a one-slide view of their entire marketing stack. It&#8217;s a great place to see how other companies are integrating multiple technologies into their marketing strategy. You can check out the 2016 MarTech Stackie awards on Scott Brinker&#8217;s blog, <a href="http://chiefmartec.com/2016/03/41-marketing-technology-stacks-2016-stackies-awards/">chiefmartec.com</a>.</p>

<h5 id="uberflipsmarketingstack">UberFlip&#8217;s Marketing Stack</h5>

<p><img src="http://cdn.chiefmartec.com/wp-content/uploads/2015/06/uberflip_marketing_tech_stack.png" alt="UberFlips Marketing Stack" /></p>

<h5 id="delphicdigitalsmarketingstack">Delphic Digital&#8217;s Marketing Stack</h5>

<p><img src="http://cdn.chiefmartec.com/wp-content/uploads/2016/03/delphic.jpg" alt="Delphic Digitals Marketing Stack" /></p>

<h4 id="gartner">Gartner</h4>

<p>Targeted at CMO&#8217;s and CTO&#8217;s, Gartner does a great job of evaluating technologies and vendors. Check out Gartner&#8217;s <a href="https://www.gartner.com/technology/research/digital-marketing/transit-map.jsp">guide to digital marketing transit</a>. (read: no paywall). <img src="https://www.gartner.com/imagesrv/marketing/img/Digi_Mktg_Map_Final_April_2015.gif;wa906e6d4fd8019817" alt="Gartner Digital Marketing Canvas" /></p>

<h4 id="othergreatsources">Other Great Sources</h4>

<p><a href="http://marketingland.com/">Marketing Land | Digital Marketing &amp; Martech News, Tactics &amp; Strategies</a><br>
 <a href="http://techcrunch.com/tag/marketing/">Marketing | TechCrunch</a><br>
 <a href="http://chiefmartec.com/">Chief Marketing Technologist - Marketing Technology Management</a></p>
            </div>
        </div>
    </div>
</article>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>